
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment:
      name: development
    pool:
      vmImage: vs2017-win2016
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureFunctionApp@1
              inputs:
                azureSubscription: 'MAIC - TEK Experts CR - v-doort - Group#1(9e9e1a84-e844-4b3c-a731-23d189b43a2e)'
                appType: 'functionAppLinux'
                appName: 'crulateAzFunc'
                deployToSlotOrASE: true
                resourceGroupName: 'crulateAzureFunction'
                slotName: 'production'
                package: '$(System.DefaultWorkingDirectory)/**/*.zip'